name: Continuous Integration

on:
  push:
    branches:
      - main  # Adjust this to your default branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version used in your project, e.g., '3.7', '3.8', '3.9', etc.

    - name: Install Poetry dependencies
      run: |
        pip install poetry
        poetry install

    - name: Build Docker image
      run: docker build -t name-generater .

    - name: Run pytest inside Docker container
      run: docker run --rm name-generater poetry run pytest
